CREATE OR ALTER PROCEDURE dbo.proc_deleteBook
    @BOOK_ID INT
AS
	DECLARE		@BOOK_DELETED BIT ;
    DELETE		dbo.BOOK
    WHERE       BOOK_ID = @BOOK_ID
	SET			@BOOK_DELETED = @@ROWCOUNT;
	SELECT		@BOOK_DELETED AS BOOK_DELETED