CREATE OR ALTER PROCEDURE dbo.proc_GetBooksForAuthor
@AUTHOR_ID INT
AS
SELECT		B.*
FROM		AUTHOR				AS A
INNER JOIN	BOOK_X_AUTHOR		AS B_X_A
ON			B_X_A.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN	BOOK				AS B
ON			B.BOOK_ID = B_X_A.BOOK_ID
WHERE		A.AUTHOR_ID = @AUTHOR_ID