--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO
-- =============================================
-- Author:		Rasmus Gormsbøl Larsen
-- Create date: 02-12-2020
-- Description:	Oprettelse af ny forfatter
-- =============================================
CREATE OR ALTER PROCEDURE dbo.proc_InsertOrUpdateAuthor
	@FIRST_NAME	VARCHAR(250),
	@LAST_NAME VARCHAR(250),
	@NATIONALITY_SHORT VARCHAR(5) = NULL,
	@DESCRIPTION VARCHAR(MAX) = NULL,
	@AUTHOR_ID INT = 0
AS
BEGIN
	
IF @AUTHOR_ID = 0
	BEGIN
		--INSERT
		INSERT INTO [dbo].[AUTHOR] ([FIRST_NAME], [LAST_NAME], [NATIONALITY_SHORT], [DESCRIPTION])
		VALUES (@FIRST_NAME, @LAST_NAME, @NATIONALITY_SHORT, @DESCRIPTION)
		SELECT SCOPE_IDENTITY() AS AUTHOR_ID;
	END
ELSE
	BEGIN
		--UPDATE
		UPDATE [dbo].[AUTHOR]
			SET [FIRST_NAME] = @FIRST_NAME, [LAST_NAME] = @LAST_NAME, [NATIONALITY_SHORT] = @NATIONALITY_SHORT, [DESCRIPTION] = @DESCRIPTION, [MODIFIED] = CURRENT_TIMESTAMP
		WHERE [AUTHOR_ID] = @AUTHOR_ID
		SELECT		*
		FROM		AUTHOR
		WHERE		AUTHOR_ID = @AUTHOR_ID;
	END
END